### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by ubalklen** [facelessuser/soupsieve#250] opened 2022-06-15 19:09 UTC
There is something wrong with the package's permissions. I'm getting a `PermissionError: [Errno 13] Permission denied: 'C:\\Users\\username\\Miniconda3\\envs\\my_env\\lib\\site-packages\\soupsieve-2.3.2.post1.dist-info\\license_files'` when trying to access the files from other programs. I stumbled upon it when trying to [cx_freeze](https://cx-freeze.readthedocs.io/) a project. Here is a reproduction:

main.py:
```
from bs4 import BeautifulSoup

html_doc = """<html><head><title>The Dormouse's story</title></head>
<body>
<p class="title"><b>The Dormouse's story</b></p>

<p class="story">Once upon a time there were three little sisters; and their names were
<a href="http://example.com/elsie" class="sister" id="link1">Elsie</a>,
<a href="http://example.com/lacie" class="sister" id="link2">Lacie</a> and
<a href="http://example.com/tillie" class="sister" id="link3">Tillie</a>;
and they lived at the bottom of a well.</p>

<p class="story">...</p>
"""
soup = BeautifulSoup(html_doc, "html.parser")
print(soup.prettify())
```

Now, if I try to freeze this file using `cxfreeze main.py`, I get the error.

This only happens in versions 2.3.2 and 2.3.2.post1. I tried 2.3.1 and it works fine.

**Comment by facelessuser** [comment] 2022-06-15 20:12
1. You haven't really provided me with a way to reproduce this. I don't use `cxfreeze`, so I don't know what you are doing. Please provide step by step instructions to reproduce.
2. Did you install via `pip`? I don't control the permissions of when an installation occurs. As long as the permissions in the wheel and tarball are reasonable, there is nothing else I can do. It is possible that there could be an issue with either `pip` or the build backend that is used (["hatchling"](https://github.com/pypa/hatch)). I guess there could even be an issue with `cxfreeze`. 

I do not see any permission issues on my machine:

```console
➜  soupsieve-2.3.2.post1.dist-info ls -la
total 40
drwxr-xr-x    9 facelessuser  admin   288 May 21 06:54 .
drwxrwxr-x  226 root          admin  7232 Jun  9 09:38 ..
-rw-r--r--    1 facelessuser  admin     4 May 21 06:54 INSTALLER
-rw-r--r--    1 facelessuser  admin  5651 May 21 06:54 METADATA
-rw-r--r--    1 facelessuser  admin  1617 May 21 06:54 RECORD
-rw-r--r--    1 facelessuser  admin     0 May 21 06:54 REQUESTED
-rw-r--r--    1 facelessuser  admin    83 May 21 06:54 WHEEL
-rw-r--r--    1 facelessuser  admin     0 May 21 06:54 entry_points.txt
drwxr-xr-x    3 facelessuser  admin    96 May 21 06:54 license_files
```

```console
➜  soupsieve-2.3.2.post1.dist-info ls -la license_files/
total 8
drwxr-xr-x  3 facelessuser  admin    96 May 21 06:54 .
drwxr-xr-x  9 facelessuser  admin   288 May 21 06:54 ..
-rw-r--r--  1 facelessuser  admin  1096 May 21 06:54 LICENSE.md
```

I would create a reproducible example, but understand, that we test for proper installation through pip, which currently is not faulty. We do not use, nor test for `cxfreeze` functionality.

If the generated wheel and tarball are created in an acceptable way, there is nothing that we can do directly. If we are creating malformed packages, then it is more likely an issue with the build backend. If the issue is the files are copied incorrectly to the `site-packages` during installation, it may be possible there is an issue with either the build backend used during installation, pip, or maybe the way it is installed on your specific machine due to some local issue or configuration.

I am most interested if this is reproducible on other machines, and specifically, if there is anything malformed in our package creation. Currently, I see no issues in permissions when extracting our built wheels and tarballs. As shown above, it appears to be copied properly as well. It would be interesting to see how reproducible this is on other systems.

**Comment by facelessuser** [comment] 2022-06-15 20:52
It is certainly possible that a package could include multiple license files. SoupSieve packages the license using a different mechanism, and, for whatever reason, is using an approach to store the license in a generic way that supports not only one, but multiple licenses, hence the plural name `license_files`. All of this is properly recorded in the RECORD file:

```
soupsieve-2.3.2.post1.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
soupsieve-2.3.2.post1.dist-info/METADATA,sha256=Dx7YfeBAf1_9MbAorGo86eFBPso-T0tTnW7GvKdaIdM,5651
soupsieve-2.3.2.post1.dist-info/RECORD,,
soupsieve-2.3.2.post1.dist-info/REQUESTED,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
soupsieve-2.3.2.post1.dist-info/WHEEL,sha256=sb4ZHsmozXdkdXRvpMHZmhxsxQvL8DERDUEGA9tAfc8,83
soupsieve-2.3.2.post1.dist-info/entry_points.txt,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
soupsieve-2.3.2.post1.dist-info/license_files/LICENSE.md,sha256=vGYjTK3T9ueq9xYPrxZfP4af_IoRtrDWxEouKoMxTdA,1096
```

`cxfreeze` should update to be aware that license files can be included as a directory.

I will consider this as an upstream issue that should be taken to `cxfreze` and will close this issue.

**Closed by facelessuser** 2022-06-15 20:52 UTC
Labels: S: invalid, S: more-info-needed, S: triage

**Comment by ofek** [comment] 2022-06-20 19:34
FYI all backends will do this soon https://peps.python.org/pep-0639/#license-files-in-project-formats
