### ISSUE TITLE
Invalid syntax error on python3.4

### ISSUE THREAD

**Issue by scf37** [facelessuser/soupsieve#245] opened 2022-04-16 07:14 UTC
```
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/opt/dad.py", line 4, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python3.4/dist-packages/bs4/__init__.py", line 38, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python3.4/dist-packages/bs4/builder/__init__.py", line 7, in <module>
    from bs4.element import (
  File "/usr/local/lib/python3.4/dist-packages/bs4/element.py", line 12, in <module>
    import soupsieve
  File "/usr/local/lib/python3.4/dist-packages/soupsieve/__init__.py", line 29, in <module>
    from . import css_parser as cp
  File "/usr/local/lib/python3.4/dist-packages/soupsieve/css_parser.py", line 4, in <module>
    from . import util
  File "/usr/local/lib/python3.4/dist-packages/soupsieve/util.py", line 59
    f"'{func.__name__}' is deprecated. {message}",
                                                ^

```

**Comment by facelessuser** [comment] 2022-04-16 12:27
What version of soupsieve are you using, because event versions do not support python 3.4.

**Comment by facelessuser** [comment] 2022-04-16 12:27
Also, can you provide a reproducible case?

**Comment by scf37** [comment] 2022-04-16 12:34
I guess I'm using latest version, installed it today via pip3. I guess I'll have to downgrade bs4 or upgrade python.

**Comment by facelessuser** [comment] 2022-04-16 12:48
I think you might get away with the 1.9 series on python 3.4. I don't recall exactly if it works though. If not, maybe an even earlier version. Granted, it may have bugs long since fixed in later releases. Generally though, I'd recommend moving to a python version that has not reached "end of line". I also realize that it is not always possible for some people.

**Comment by scf37** [comment] 2022-04-16 14:17
1.9 and 1.8 did not work.
Downgrading to `beautifulsoup4==4.5.3` helped

**Closed** 2022-04-16 14:17 UTC
Labels: S: triage
