### ISSUE TITLE
Readme when showing supported css selectors.

### ISSUE THREAD

**Issue by yjqiang** [facelessuser/soupsieve#52] opened 2018-12-31 02:57 UTC
Before `and many more`

After [and many more](https://facelessuser.github.io/soupsieve/selectors/)

**Comment by facelessuser** [comment] 2018-12-31 02:59
Care to elaborate?  I'm not sure what is being referenced here, and what the issue is.

**Comment by yjqiang** [comment] 2018-12-31 03:00
When I want to check all the css selectors, I have to open the document and find the target, and click the link. So I think it would be convenient for users to check.

**Comment by facelessuser** [comment] 2018-12-31 03:03
Oh, you want it to link to the document page.  I guess you could bookmark it 🙂 too . I'm open to a pull request, if not, I'll get to it when I get a chance.

**Comment by facelessuser** [comment] 2018-12-31 04:38
Closed via #53

**Closed by facelessuser** 2018-12-31 04:38 UTC
Labels: docs
